### ISSUE TITLE
No "type" entry for file

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/zenodoReports#2]
Command:

```
python3 ~/zenodoReports/launch.py report kbnl-2023-11-08.json
```

Results in:

```
Traceback (most recent call last):
  File "/home/johan/zenodoReports/launch.py", line 8, in <module>
    main()
  File "/home/johan/zenodoReports/zenodoReports/zenodoReports.py", line 92, in main
    report.report(metadataIn)
  File "/home/johan/zenodoReports/zenodoReports/report.py", line 293, in report
    ftype = file["type"]
KeyError: 'type'
```

Which refers to this bit of report.py:

```python
        for file in files:
            ftype = file["type"]
            fileTypes.append(ftype)
```
Inspection of latest Zenodo JSON dump shows that each file element no longer contains "type" entry.  Not sure if this is an intentional change or a bug introduced in the October 2023 overhaul of Zenodo.

**Comment by bitsgalore** [comment]
As a workaround I disabled file type reporting:

<https://github.com/KBNLresearch/zenodoReports/commit/eb1b3b376cb659704628955e78034461666ff338>

Created the following Zenodo issue:

<https://github.com/zenodo/zenodo/issues/2504>
